### ISSUE TITLE
More than snippet identifier is consumed

### ISSUE THREAD

**Issue by ghost** [henricattoire/aergia#5]
Defined snippet `test`:
```
function a() {
	<{+}>
}
```
### Start of the snippet

Expanding this in a file: ( | is cursor ) `(test|` will result to
```
function a() {
	|
}
```

Instead of the expected:
```
(function a() {
	|
}
```
### End of the snippet

This also happens with stuff on the end of the line. This: `test|abcd` should expand to
```
function a() {
	|
}abcd
```
But currently expands to:
```
function a() {
	|
}
```

**Comment by henricattoire** [comment]
I also encountered that already and was planning on fixing it whenever I had time. Because this seems to be especially frustrating in js as you might want to write

const Name = func<c-a>

And you would expect it to expand to:

const Name = function() {
   <{+}>
}

But aergia sucks everything up which is not ideal, so you get:

function() {
   <{+}>
}

I’ll add it to the project board when I look at the indenting issue tonight
